on:
  push:
    tags:
      - '*'

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Upload tag to WPFactory
    steps:

      - uses: wpcodefactory/wpfactory-product-updater-github-action@master
        id: update
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          api_token: ${{ secrets.WPFACTORY_PRODUCT_UPDATER_API_TOKEN }}
          product_id: 8864
          product_filename: download-plugins-from-dashboard

      - name: WP API Response
        if: always()
        run: echo Response from URL - ${{ steps.update.outputs.response }}
